### ISSUE TITLE
sftp kio broken

### ISSUE THREAD

**Issue by llelectronics** [blue-systems/netrunner-next#35] opened 2019-08-05 17:03 UTC
Sftp Kio accepts an unknown key shows content and opening files or folders results in an error message about no known keys found only keys with a different key type. 

![image](https://user-images.githubusercontent.com/3415572/62481759-a2363000-b7b3-11e9-9217-3529c48a5baf.png)

P.S. fish kio works fine with the key.

**Comment by ScarlettGatelyMoore** [comment] 2019-08-05 18:01
@llelectronics I can't reproduce. I even created ecdsa keys on both.
![VirtualBox_Netrunner Desktop_05_08_2019_11_00_39](https://user-images.githubusercontent.com/1056501/62485032-69289c00-b770-11e9-9643-fac1605c555e.png)

**Comment by star-buck** [comment] 2019-08-06 18:27
How come you have such a huge panel in your screenshot, when it is still 30pixels here??

**Comment by ScarlettGatelyMoore** [comment] 2019-08-06 19:06
I hit the panel bug discussed in telegram - now fixed

**Comment by ScarlettGatelyMoore** [comment] 2019-08-09 18:40
Still can't reproduce latest image

**Closed** 2024-05-09 01:06 UTC
Labels: bug
